version: '3.8'

services:
  blog_post_summarizer:
    image: viramyashah/blog_post_summarizer:latest
    ports:
      - "8501:8501"
    volumes:
      - ${pwd}/data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}