version: '3.8'

services:
  blog_post_summarizer:
    image: blog_post_summarizer:0.7
    ports:
      - "8501:8501"
    volumes:
      - ${pwd}/data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}