name: CI for Blog Post Summary App

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub (optional, if pushing images)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: docker build -t blog_post_summarizer .

    # Step 5: Push the image to Docker Hub (optional)
    - name: Tag Docker image to Docker Hub
      run: docker tag blog_post_summarizer viramyashah/blog_post_summarizer:latest 
      
    - name: Push docker image
      run: docker push viramyashah/blog_post_summarizer:latest